[[redirects]]
  from = "/api/*"
  to = "http://production-env.eba-xqpdsyrp.eu-north-1.elasticbeanstalk.com/api/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200